import React, { createContext, useContext, useState, useEffect, useRef, useCallback, useMemo } from 'react';

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: 'en', label: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  { code: 'kn', label: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', label: 'Malayalam', native: 'മലയാളം', flag: '🇮🇳' },
];

// Comprehensive Agricultural & UI Dictionary for Local Farmers (Multi-lingual)
export const FARMER_DICTIONARY = {
  ta: {
    // Specific Dashboard Words Specified by User
    'pH Level': 'pH அளவு',
    'Water Tank': 'தண்ணீர் தொட்டி',
    'Status': 'நிலை',
    'OFF': 'ஆஃப்',
    'ON': 'ஆன்',
    'Sensor Overview': 'சென்சார் மேலோட்டம்',
    'AI Recommendations': 'AI பயிர் பரிந்துரைகள்',
    'View All': 'அனைத்தையும் காண்',
    'Top 3 Suitable': 'சிறந்த 3 உகந்த',
    'Maize': 'மக்காச்சோளம்',
    'Quick Actions': 'விரைவு செயல்பாடுகள்',
    'Recommendation': 'பரிந்துரை',
    'Field Telemetry &': 'புல அளவீடுகள் &',
    'NODES ONLINE': 'முனைகள் இணைப்பில்',
    'Manage Nodes': 'முனைகளை நிர்வகி',
    'Manage Nodes →': 'முனைகளை நிர்வகி →',
    'Field': 'புலம்',
    'Polyhouse': 'பசுமைக்குடில்',
    'Drip Lines': 'சொட்டுநீர் கோடுகள்',
    'Battery': 'பேட்டரி',
    'Signal': 'சிக்னல்',
    'View History': 'வரலாற்றைக் காண்',
    'Click to upload or drag & drop': 'பதிவேற்ற கிளிக் செய்யவும் அல்லது இழுத்து விடவும்',
    'Result': 'முடிவு',
    'Late Blight': 'இலை கருகல் நோய்',
    'Severity': 'தீவிரம்',
    'Confidence': 'நம்பிக்கை',
    'Affected Area': 'பாதிக்கப்பட்ட பகுதி',
    'Diseased Leaf': 'பாதிக்கப்பட்ட இலை',
    'Treatment Steps': 'சிகிச்சை முறைகள்',
    'Remove infected leaves': 'பாதிக்கப்பட்ட இலைகளை அகற்றுங்கள்',
    'Use Copper based fungicide': 'காப்பர் பூஞ்சாணி மருந்தைப் பயன்படுத்துங்கள்',
    'Maintain proper spacing': 'சரியான இடைவெளியைப் பராமரிக்கவும்',
    'Mode': 'முறை',
    'Auto Mode': 'தானியங்கி முறை',
    'Manual Mode': 'கைமுறை பாசனம்',
    'Threshold': 'எல்லை வரம்பு',
    'Next': 'அடுத்த',
    'Next பாசனம்': 'அடுத்த பாசனம்',
    'Tomorrow, 07:00 AM': 'நாளை, காலை 07:00 மணி',
    'Tomorrow': 'நாளை',
    'Turn ON': 'இயக்கு',
    'Turn OFF': 'நிறுத்து',
    'Recent': 'சமீபத்திய',
    'Recent எச்சரிக்கைகள்': 'சமீபத்திய எச்சரிக்கைகள்',
    'Alert': 'எச்சரிக்கை',
    'min ago': 'நிமிடங்களுக்கு முன்',
    'hour ago': 'மணிநேரத்திற்கு முன்',
    'is below': 'குறைவாக உள்ளது',
    'Turned OFF': 'நிறுத்தப்பட்டது',
    'stopped automatically': 'தானாக நிறுத்தப்பட்டது',
    'Rain Detected': 'மழை கண்டறியப்பட்டது',
    'Rain detected in your area': 'உங்கள் பகுதியில் மழை கண்டறியப்பட்டது',
    'Tank level is below 20%': 'தொட்டி நீர் அளவு 20% க்கும் குறைவாக உள்ளது',
    'Overview': 'மேலோட்டம்',
    '7 Days': '7 நாட்கள்',
    'Last 7 Days': 'கடந்த 7 நாட்கள்',
    'Today': 'இன்று',
    'Yesterday': 'நேற்று',
    'Crop Recommendation': 'பயிர் பரிந்துரை',
    'Disease Diagnosis': 'தாவர நோய் கண்டறிதல்',
    'Sensor Monitoring': 'சென்சார் கண்காணிப்பு',
    'Weather Forecast': 'வானிலை முன்னறிவிப்பு',
    'Partly Cloudy': 'பகுதியளவு மேகமூட்டம்',
    'Wind': 'காற்று',
    'Rain': 'மழை',
    'Sat': 'சனி',
    'Sun': 'ஞாயிறு',
    'Mon': 'திங்கள்',
    'Tue': 'செவ்வாய்',
    'Wed': 'புதன்',
    'Thu': 'வியாழன்',
    'Fri': 'வெள்ளி',
    'Water Usage': 'நீர் பயன்பாடு',
    'Time': 'நேரம்',
    'Energy Used': 'பயன்படுத்தப்பட்ட மின்சாரம்',
    'Controller': 'கட்டுப்பாட்டாளர்',
    'Relay Module': 'ரிலே தொகுதி',
    'Farm Map': 'பண்ணை வரைபடம்',
    'View Full Map': 'முழு வரைபடத்தைக் காண்',
    'Satellite View': 'செயற்கைக்கோள் பார்வை',
    'Farm Map Satellite View': 'பண்ணை வரைபடம் செயற்கைக்கோள் பார்வை',
    'JPG, PNG, WebP (Max 5MB)': 'JPG, PNG, WebP (அதிகபட்சம் 5MB)',

    // Core Agriculture & Farming
    'Farm': 'பண்ணை',
    'Farms': 'பண்ணைகள்',
    'Farms Management': 'பண்ணைகள் மேலாண்மை',
    'Crop': 'பயிர்',
    'Crops': 'பயிர்கள்',
    'Soil': 'மண்',
    'Land': 'நிலம்',
    'Yield': 'மகசூல்',
    'Harvest': 'அறுவடை',
    'Irrigation': 'பாசனம்',
    'Smart Irrigation': 'நுண்ணீர் பாசனம்',
    'Pumps': 'பம்புகள்',
    'Pump': 'பம்ப்',
    'Fertilizer': 'உரம்',
    'Nitrogen': 'தழைச்சத்து (N)',
    'Phosphorus': 'மணிச்சத்து (P)',
    'Potassium': 'சாம்பல்ச்சத்து (K)',
    'Weather': 'வானிலை',
    'Forecast': 'முன்னறிவிப்பு',
    'Rainfall': 'மழையளவு',
    'Moisture': 'ஈரப்பதம்',
    'Soil Moisture': 'மண் ஈரப்பதம்',
    'Soil Moisture %': 'மண் ஈரப்பதம் %',
    'Volumetric Soil Moisture': 'மண் ஈரப்பதம் அளவு',
    'Moist': 'ஈரப்பதம் கொண்டது',
    'Soil pH': 'மண் pH அளவு',
    'Soil pH Levels': 'மண் pH அளவுகள்',
    'Soil pH Balance': 'மண் pH சமநிலை',
    'Slightly Acidic': 'சிறிது அமிலத்தன்மை',
    'Ideal Range: 6.0 - 7.0': 'உகந்த வரம்பு: 6.0 - 7.0',
    'Water Tank Level': 'தண்ணீர் தொட்டி நீர் அளவு',
    'Adequate': 'போதுமானது',
    'Solenoid Drip Pump Status': 'சொட்டுநீர் பம்ப் நிலை',
    'Manual Pump Relay Control': 'கைமுறை பம்ப் ரிலே கட்டுப்பாடு',
    'Pump ON': 'பம்ப் இயங்குகிறது',
    'Pump OFF': 'பம்ப் நிறுத்தப்பட்டுள்ளது',
    'Override automated rules to manually start or halt 12V solenoid drip irrigation pump.': '12V சொட்டுநீர் பாசன பம்பை கைமுறையாக இயக்க அல்லது நிறுத்த தானியங்கி விதிகளை மாற்றி அமைக்கவும்.',
    'Turn ON Pump Relay': 'பம்ப் ரிலேயை இயக்கு',
    'Turn OFF Pump Relay': 'பம்ப் ரிலேயை நிறுத்து',
    'Smart Drip Irrigation Threshold Rules': 'நுண்ணீர் பாசன எல்லை வரம்பு விதிகள்',
    'Trigger Pump ON Below Moisture': 'ஈரப்பதம் இந்த அளவுக்கு கீழே குறைந்தால் பம்பை இயக்கு',
    'Rain Sensor Auto-Override': 'மழை சென்சார் தானியங்கி நிறுத்தம்',
    'Save Automation Rules': 'தானியங்கி விதிகளைச் சேமி',
    'Rules Updated!': 'விதிகள் புதுப்பிக்கப்பட்டன!',
    'Stop Solenoid Pump': 'சொட்டுநீர் பம்பை நிறுத்து',
    'Start Solenoid Pump': 'சொட்டுநீர் பம்பை இயக்கு',
    'vs last hour average': 'கடந்த மணிநேர சராசரியுடன் ஒப்பிடுகையில்',
    'Normal': 'இயல்பானது',
    'Temperature': 'வெப்பநிலை',
    'Ambient Temperature': 'சுற்றுப்புற வெப்பநிலை',
    'Humidity': 'காற்றின் ஈரப்பதம்',
    'Relative Humidity': 'காற்றின் ஒப்பீட்டு ஈரப்பதம்',
    'Micro-Climate': 'சுற்றுச்சூழல் காலநிலை',
    'Sensors': 'சென்சார்கள்',
    'Sensor Monitoring': 'சென்சார் கண்காணிப்பு',

    // AI Advisor Keys
    'ai_crop_title': 'AI பயிர் பரிந்துரை இயந்திரம்',
    'ai_crop_subtitle': 'மண் மற்றும் வானிலை அளவீடுகளின் அடிப்படையில் இயந்திர கற்றல்',
    // Weather Page Individual Metric Cards & Interactive Chart
    'Local Microclimate Weather': 'உள்ளூர் நுண்-காலநிலை வானிலை',
    'Real-Time Microclimate Weather Intelligence': 'நிகழ்நேர நுண்-காலநிலை வானிலை தகவல்கள்',
    'Individual Weather Parameter Cards': 'தனிப்பட்ட வானிலை அளவுருக்கள்',
    'Interactive Weather Analytics Chart': 'செயல்பாட்டு வானிலை வரைபடம்',
    'Time Horizon': 'கால வரம்பு',
    '24 Hours': '24 மணிநேரம்',
    '7 Days': '7 நாட்கள்',
    '30 Days': '30 நாட்கள்',
    'Toggle Metrics': 'அளவீடுகளை மாற்றுக',
    'Hover over any data point for detailed microclimate readings.': 'விரிவான அளவீடுகளுக்கு வரைபடத்தின் புள்ளிகள் மீது கர்சரை நகர்த்தவும்.',
    'Microclimate Spotlight': 'காலநிலை சிறப்பம்சங்கள்',
    'Selected Period': 'தேர்ந்தெடுக்கப்பட்ட காலம்',
    'Light Rain': 'லேசான மழை',
    'Showers': 'மழைச்சாரல்',
    'Clear': 'தெளிவான வானிலை',
    'Sunny': 'வெயில்',
    'Temperature & Heat Index': 'வெப்பநிலை & வெப்பக் குறியீடு',
    'Real-Time Microclimate Weather Intelligence': 'நிகழ்நேர நுண்-காலநிலை வானிலை தகவல்கள்',
    'Individual Weather Parameter Cards': 'தனிப்பட்ட வானிலை அளவுருக்கள்',
    'Temperature & Heat Index': 'வெப்பநிலை & வெப்பக் குறியீடு',
    'Feels Like': 'உணரப்படும் வெப்பநிலை',
    'Min / Max Temp': 'குறைந்தபட்ச / அதிகபட்ச வெப்பநிலை',
    'Dew Point': 'பனிப்புள்ளி',
    'Evapotranspiration (ET0)': 'நீராவிப்போக்கு (ET0)',
    'Moisture Comfort': 'ஈரப்பதம் ஆறுதல்',
    'Wind & Gust Dynamics': 'காற்று & புயல் வேகம்',
    'Wind Direction': 'காற்றின் திசை',
    'Wind Gust': 'காற்றின் பெருவேகம்',
    'Barometric Pressure': 'வளிமண்டல அழுத்தம்',
    'Pressure Trend': 'அழுத்தப் போக்கு',
    'Solar Radiation & UV': 'சூரிய கதிர்வீச்சு & UV',
    'UV Index': 'UV குறியீடு',
    'Solar Radiation': 'சூரிய ஒளி கதிர்வீச்சு',
    'Sunrise / Sunset': 'சூரியோதயம் / சூரிய அஸ்தமனம்',
    'Precipitation & Rain Risk': 'மழை & மழைப்பொழிவு சாத்தியக்கூறு',
    'Rain Probability': 'மழை சாத்தியம்',
    '24h Rain Accumulation': '24 மணிநேர மழை சேமிப்பு',
    '7-Day Agronomic Forecast': '7 நாட்கள் வேளாண் வானிலை முன்னறிவிப்பு',
    '24-Hour Hourly Weather Trend': '24 மணிநேர வானிலை போக்கு',
    'Rain': 'மழை',
    'Barometer': 'அழுத்தமானி',
    'ai_soil_ph': 'மண் pH அளவு',
    'ai_moisture': 'மண் ஈரப்பதம்',
    'ai_temp': 'வெப்பநிலை',
    'ai_rainfall': 'மழையளவு',
    'ai_run_recommendation': 'AI பயிர் பரிந்துரையை இயக்கு',
    'ai_analyzing': 'காலநிலை தரவுகள் பகுப்பாய்வு செய்யப்படுகின்றன...',
    'ai_recommended_crop': 'பரிந்துரைக்கப்பட்ட பயிர்',
    'ai_match_confidence': 'வேளாண் பொருத்த நம்பிக்கை',

    // Disease Diagnostics Upload Keys
    'Upload Leaf Image for CV Diagnostics': 'கணினி பார்வை நோய் கண்டறிதலுக்கு இலை புகைப்படத்தைப் பதிவேற்றவும்',
    'Scan plant leaves to detect fungal, bacterial, or viral pathogens': 'பூஞ்சை, பாக்டீரியா அல்லது வைரஸ் நோய்களைக் கண்டறிய தாவர இலைகளை ஸ்கேன் செய்யவும்',
    'Drag and drop your leaf photo here': 'உங்கள் இலை புகைப்படத்தை இங்கே இழுத்து விடவும்',
    'Supports JPG, PNG, WEBP (Max 10MB)': 'JPG, PNG, WEBP கோப்புகள் ஏற்கும் (அதிகபட்சம் 10MB)',
    'Select Photo': 'புகைப்படத்தைத் தேர்ந்தெடு',
    'Choose Different Photo': 'வேறு புகைப்படத்தைத் தேர்ந்தெடு',
    'Run Disease Classification': 'நோய் வகைப்பாட்டை இயக்கு',
    'Scanning Vision Model...': 'விஷன் மாடல் ஸ்கேன் செய்கிறது...',

    // Analytics & Reports Keys
    'Weekly Water Consumption (Liters)': 'வாராந்திர நீர் பயன்பாடு (லிட்டர்களில்)',
    'Total: 3,380 L': 'மொத்தம்: 3,380 லிட்டர்கள்',
    'Telemetry Moisture vs Temp Trend': 'ஈரப்பதம் மற்றும் வெப்பநிலை போக்கு',
    'Yield Growth Performance': 'மகசூல் வளர்ச்சி திறன்',
    '+18.5% Efficiency': '+18.5% திறன்',
    'Tomato ( Rome )': 'தக்காளி (ரோம்)',
    'Potato ( Kufri )': 'உருளைக்கிழங்கு (குஃப்ரி)',
    '28.5 Tons / Acre': '28.5 டன்கள் / ஏக்கர்',
    '24.0 Tons / Acre': '24.0 டன்கள் / ஏக்கர்',
    'Export Analytics Reports': 'பகுப்பாய்வு அறிக்கைகளை ஏற்றுமதி செய்',
    'Download formatted telemetry summaries, irrigation volume logs, and AI yield diagnostic reports.': 'சென்சார் அறிக்கைகள், பாசன அளவுகள் மற்றும் AI மகசூல் அறிக்கைகளைப் பதிவிறக்கவும்.',
    'Export as PDF Report': 'PDF அறிக்கையாகப் பதிவிறக்கு',
    'Export Excel (.xlsx)': 'Excel (.xlsx) கோப்பாகப் பதிவிறக்கு',

    // Notification Feed Keys
    'System Notification Feed': 'கணினி எச்சரிக்கை அறிவிப்புகள்',
    'Low Soil Moisture Alert': 'குறைந்த மண் ஈரப்பதம் எச்சரிக்கை',
    'Block A moisture dropped below 35%. Auto-irrigation triggered.': 'தொகுதி A ஈரப்பதம் 35% க்கும் கீழே குறைந்தது. தானியங்கி பாசனம் தொடங்கியது.',
    '10 mins ago': '10 நிமிடங்களுக்கு முன்',
    'Irrigation Cycle Complete': 'பாசன சுழற்சி முடிவடைந்தது',
    'Plot 2 drip irrigation completed (450 Liters delivered).': 'நிலம் 2 சொட்டுநீர் பாசனம் முடிந்தது (450 லிட்டர்கள் பாய்ச்சப்பட்டது).',
    '1 hour ago': '1 மணிநேரத்திற்கு முன்',
    'AI Model Scan Complete': 'AI மாதிரி ஸ்கேன் முடிந்தது',
    'Leaf scan classified as Early Blight. Copper spray advised.': 'இலை ஸ்கேன் இலை கருகல் நோயாக வகைப்படுத்தப்பட்டது. காப்பர் பூஞ்சாணி மருந்து தெளிக்க அறிவுறுத்தப்படுகிறது.',
    '3 hours ago': '3 மணிநேரத்திற்கு முன்',

    // Crops
    'Tomato': 'தக்காளி',
    'Tomato (Hybrid Rome)': 'தக்காளி (ஹைபிரிட் ரோம்)',
    'Organic Tomato': 'இயற்கை தக்காளி',
    'Rice': 'நெல்',
    'Paddy': 'நெல்',
    'Basmati Rice': 'பாஸ்மதி நெல்',
    'Rice / Paddy (Basmati 1121)': 'பாஸ்மதி நெல் (பாஸ்மதி 1121)',
    'Corn': 'மக்காச்சோளம்',
    'Sweet Corn': 'மக்காச்சோளம்',
    'Sweet Corn (Sugar 75)': 'மக்காச்சோளம் (சர்க்கரை 75)',
    'Potato': 'உருளைக்கிழங்கு',
    'Potato (Kufri Jyoti)': 'உருளைக்கிழங்கு (குஃப்ரி ஜோதி)',
    'Wheat': 'கோதுமை',
    'Cotton': 'பருத்தி',
    'Sugarcane': 'கரும்பு',

    // Navigation & Pages
    'Dashboard': 'முகப்புப்பலகை',
    'AI Advisor': 'AI பயிர் ஆலோசகர்',
    'AI Crop Advisor': 'AI பயிர் ஆலோசகர்',
    'AI Crop Advisor Engine': 'AI பயிர் ஆலோசகர் என்ஜின்',
    'Diagnosis': 'நோய் கண்டறிதல்',
    'Disease Diagnosis': 'தாவர நோய் கண்டறிதல்',
    'Disease Diagnosis AI': 'தாவர நோய் கண்டறிதல் AI',
    'Analytics': 'பகுப்பாய்வு',
    'Analytics & Insights': 'பகுப்பாய்வு & நுண்ணறிவு',
    'Reports': 'அறிக்கைகள்',
    'Farm Reports': 'பண்ணை அறிக்கைகள்',
    'Alerts': 'எச்சரிக்கைகள்',
    'Alerts & Activity': 'எச்சரிக்கைகள் & விழிப்பூட்டல்கள்',
    'Weather Forecast': 'வானிலை முன்னறிவிப்பு',
    'Devices': 'சாதனங்கள்',
    'IoT Devices': 'IoT சாதனங்கள்',
    'Settings': 'அமைப்புகள்',
    'System Settings': 'கணினி அமைப்புகள்',
    'Profile': 'சுயவிவரம்',
    'User Profile': 'பயனர் சுயவிவரம்',
    'Mobile App': 'மொபைல் செயலி',

    // Actions & Buttons
    'Run': 'இயக்கு',
    'Start': 'தொடங்கு',
    'Stop': 'நிறுத்து',
    'Edit': 'திருத்து',
    'Save': 'சேமி',
    'Delete': 'நீக்கு',
    'Search': 'தேடு',
    'Search anything... (Ctrl + K)': 'தேடுங்கள்... (Ctrl + K)',
    'Search Results': 'தேடல் முடிவுகள்',
    'Run AI Recommendation': 'AI பயிர் பரிந்துரையை இயக்கு',
    'Sync Live Telemetry': 'சென்சார் தரவை இணை',
    'Pull Sensors': 'தரவு எடு',
    'Logout': 'வெளியேறு',
    'Login': 'உள்நுழை',

    // Statuses & Units
    'Optimal': 'உகந்தது',
    'Critical': 'முக்கியமானது',
    'Connected': 'இணைக்கப்பட்டுள்ளது',
    'Disconnected': 'இணைப்பு துண்டிக்கப்பட்டது',
    'Active': 'செயலில்',
    'Offline': 'செயலிழந்தது',
    'Online': 'இணைப்பில்',
    'Moderate': 'மிதமான',
    'High': 'அதிக',
    'Low': 'குறைந்த',
    'Acre': 'ஏக்கர்',
    'Acres': 'ஏக்கர்',
    'Tons': 'டன்கள்',
    'Good Morning, Aathi! 👋': 'காலை வணக்கம், ஆதி! 👋',
    'greeting': 'காலை வணக்கம், ஆதி! 👋',
    'greeting_morning': 'காலை வணக்கம், ஆதி! 🌅',
    'greeting_afternoon': 'மதிய வணக்கம், ஆதி! ☀️',
    'greeting_evening': 'மாலை வணக்கம், ஆதி! 🌆',
    'greeting_night': 'இனிய இரவு வணக்கம், ஆதி! 🌙',
    'search_placeholder': 'தேடுங்கள்... (Ctrl + K)',
    'page_dashboard_title': 'ஆதி (முதன்மை விவசாயி)',
    'page_dashboard_sub': '📍 கோவை, தமிழ்நாடு • நேரடி சென்சார் அளவீடு',
    'page_farms_title': 'பண்ணை மேலாண்மை',
    'page_farms_sub': 'நிலப்பரப்புகள் மற்றும் பயிர்களை நிர்வகிக்கவும்',
    'page_monitoring_title': 'சென்சார் கண்காணிப்பு',
    'page_monitoring_sub': 'நேரடி IoT அளவீடுகள் மற்றும் முனைகள் நிலை',
    'page_recommendation_title': 'AI பயிர் ஆலோசகர்',
    'page_recommendation_sub': 'இயந்திர கற்றல் பயிர் பரிந்துரைகள்',
    'page_diagnosis_title': 'தாவர நோய் கண்டறிதல்',
    'page_diagnosis_sub': 'AI கேமரா இலை நோய் கண்டறிதல்',
    'page_irrigation_title': 'நுண்ணீர் பாசனம்',
    'page_irrigation_sub': 'தானியங்கி சொட்டுநீர் பம்புகள்',
    'page_analytics_title': 'பகுப்பாய்வு & அறிக்கைகள்',
    'page_analytics_sub': 'நீர் பயன்பாடு மற்றும் மின்சார தரவு',
    'page_notifications_title': 'எச்சரிக்கைகள் & விழிப்பூட்டல்கள்',
    'page_notifications_sub': 'கணினி எச்சரிக்கைகள் மற்றும் அறிவிப்புகள்',
    'page_profile_title': 'பயனர் சுயவிவரம்',
    'page_profile_sub': 'தனிப்பட்ட தகவல்கள் மற்றும் பாதுகாப்பு அமைப்புகள்',
    'page_settings_title': 'கணினி அமைப்புகள்',
    'page_settings_sub': 'அமைப்புகள் மற்றும் API திறவுகோல்கள்',
    'Units & Localization': 'அளவீடுகள் & அமைப்புகள்',
    'Sensor Thresholds': 'சென்சார் வரம்புகள்',
    'AI Model Engine': 'AI மாதிரி இன்ஜின்',
    'Alert Channels': 'எச்சரிக்கை சேனல்கள்',
    'IoT & Weather API Keys': 'IoT & வானிலை API திறவுகோல்கள்',
    'Legal & Terms of Service': 'சட்ட விதிமுறைகள்',
    'System Settings & API Keys': 'கணினி அமைப்புகள் & API திறவுகோல்கள்',
    'Save All System Settings & API Keys': 'அனைத்து அமைப்புகளையும் சேமி',
    'Temperature Scale': 'வெப்பநிலை அளவுகோல்',
    'Soil Moisture Metric': 'மண் ஈரப்பதம் அளவுகோல்',
    'Land Area Measurement': 'நிலப்பரப்பு அளவீடு',
    'System Timezone': 'கணினி நேர மண்டலம்',
    'Telemetry Alert & Pump Thresholds': 'சென்சார் எச்சரிக்கை & பம்ப் வரம்புகள்',
    'Soil pH Danger Range Warning': 'மண் pH அபாய எல்லை எச்சரிக்கை',
    'Soil Moisture Auto Irrigation Range': 'மண் ஈரப்பதம் தானியங்கி பாசன எல்லை',
    'Neural AI Recommendation Engine': 'AI பயிர் ஆலோசகர் இன்ஜின்',
    'AI Recommendation Model Version': 'AI மாதிரி பதிப்பு',
    'Minimum Match Confidence Score': 'குறைந்தபட்ச துல்லிய சதவீதம்',
    'Notification Channels & Subscriptions': 'அறிவிப்பு சேனல்கள் & விழிப்பூட்டல்கள்',
    'Email Notification Reports': 'மின்னஞ்சல் அறிக்கைகள்',
    'SMS Urgent Notifications': 'SMS அவசர எச்சரிக்கைகள்',
    'IoT Hardware & Weather API Keys': 'IoT வன்பொருள் & வானிலை API திறவுகோல்கள்',
    'OpenWeatherMap Weather API Key': 'OpenWeatherMap வானிலை API சாவி',
    'Test Weather API Key': 'வானிலை API சாவியை சோதி',
    'Automatic High-Accuracy GPS Tracker': 'தானியங்கி துல்லியமான GPS டிராக்கர்',
    'Refresh High-Accuracy GPS': 'GPS இடத்தை புதுப்பி',
    'MQTT Telemetry Broker URL': 'MQTT டேட்டா தரகர் முகவரி',
    'Legal Compliance & Terms of Service': 'சட்ட இணக்கம் & சேவை விதிகள்',
    'Review Terms & Conditions': 'விதிமுறைகளை மதிப்பாய்வு செய்',
    'Reset to Factory Defaults': 'இயல்பு நிலைக்கு மீட்டமை',
    'Export Farm Config (.JSON)': 'பண்ணை அமைப்புகளை பதிவிறக்கு (.JSON)',
    'WhatsApp & SMS Emergency Alerts': 'WhatsApp & SMS அவசர எச்சரிக்கைகள்',
    'Primary Farmer Phone Number': 'முதன்மை விவசாயி தொலைபேசி எண்',
    'Secondary Emergency Contact': 'இரண்டாம் நிலை அவசர தொடர்பு',
    'WhatsApp Instant Dispatch': 'உடனடி WhatsApp அறிவிப்புகள்',
    'Alert Trigger Conditions': 'எச்சரிக்கை தூண்டுதல் நிபந்தனைகள்',
    'Pump Dry-Run & Low Water Level': 'பம்ப் நீர் பற்றாக்குறை எச்சரிக்கை',
    'Extreme Heat Stress (> 38°C)': 'அதிக வெப்ப அலை எச்சரிக்கை (> 38°C)',
    'Critical Soil Acidic Warning (< 5.0 pH)': 'மண் அமிலத்தன்மை எச்சரிக்கை (< 5.0 pH)',
    'Heavy Rainfall & Flood Alert': 'கனமழை & வெள்ள எச்சரிக்கை',
    'Send Test WhatsApp Alert': 'சோதனை WhatsApp செய்தியை அனுப்பு',
    'Send Test SMS Alert': 'சோதனை SMS செய்தியை அனுப்பு',
    'Account': 'கணக்கு அமைப்புகள்',
    'Personal Information': 'தனிப்பட்ட தகவல்கள்',
    'Password': 'கடவுச்சொல்',
    'Sessions': 'செயலில் உள்ள அமர்வுகள்',
    'Farm': 'பண்ணை அமைப்புகள்',
    'Farm Information': 'பண்ணை விவரங்கள்',
    'Crop Information': 'பயிர் விவரங்கள்',
    'Farm Preferences': 'பண்ணை விருப்பத்தேர்வுகள்',
    'Irrigation': 'பாசன அமைப்புகள்',
    'Manual / Automatic': 'கையால் / தானியங்கி பாசனம்',
    'Moisture Threshold': 'ஈரப்பதம் எல்லை',
    'Rain Condition': 'மழை நிபந்தனை',
    'Tank Protection': 'தொட்டி பாதுகாப்பு',
    'Maximum Runtime': 'அதிகபட்ச இயங்கும் நேரம்',
    'Sensors': 'சென்சார்கள்',
    'Temperature': 'வெப்பநிலை',
    'Humidity': 'காற்றில் ஈரப்பதம்',
    'Soil Moisture': 'மண் ஈரப்பதம்',
    'Soil pH': 'மண் pH',
    'Automation': 'தானியங்கி விதிகள்',
    'Irrigation Rules': 'பாசன விதிகள்',
    'Alert Rules': 'எச்சரிக்கை விதிகள்',
    'AI': 'செயற்கை நுண்ணறிவு (AI)',
    'Crop Recommendation': 'பயிர் பரிந்துரை',
    'Disease Diagnosis': 'நோய் கண்டறிதல்',
    'Devices': 'IoT சாதனங்கள்',
    'IoT Devices': 'IoT சாதனங்கள்',
    'Connection': 'இணைப்பு',
    'Notifications': 'அறிவிப்புகள்',
    'Language': 'மொழி',
    'Units': 'அளவீட்டு அலகுகள்',
    'Date & Time': 'தேதி & நேரம்',
    'Appearance': 'தோற்றம் & தீம்',
    'Privacy & Security': 'தனியுரிமை & பாதுகாப்பு',
    'Data & Export': 'தரவு & ஏற்றுமதி',
    'Help & Support': 'உதவி & ஆதரவு',
    'About': 'பற்றி',
    'nav_dashboard': 'டாஷ்‌போர்டு',
    'nav_farms': 'பண்ணைகள்',
    'nav_sensors': 'சென்சார்கள்',
    'nav_irrigation': 'நுண்ணீர் பாசனம்',
    'nav_recommendation': 'AI பயிர் ஆலோசகர்',
    'nav_diagnosis': 'நோய் கண்டறிதல்',
    'nav_analytics': 'பகுப்பாய்வு',
    'nav_reports': 'அறிக்கைகள்',
    'nav_notifications': 'அறிவிப்புகள்',
    'nav_weather': 'வானிலை',
    'nav_devices': 'IoT சாதனங்கள்',
    'nav_settings': 'அமைப்புகள்',
    'nav_mobile_showcase': 'மொபைல் செயலி',
    'page_weather_title': 'வானிலை அறிக்கை',
    'page_weather_sub': 'நேரலை ஈரப்பதம், மழை வாய்ப்பு மற்றும் காலநிலை பகுப்பாய்வு',

    // Authentication & Registration Page Translations
    'Welcome Back': 'மீண்டும் வருக',
    'Sign in to monitor real-time IoT sensors & AI crop health': 'நேரடி IoT சென்சார்கள் மற்றும் AI பயிர் ஆரோக்கியத்தைக் கண்காணிக்க உள்நுழையவும்',
    'Farm Manager': 'பண்ணை மேலாளர்',
    'Lead Farmer': 'முதன்மை விவசாயி',
    'Email or Phone Number': 'மின்னஞ்சல் அல்லது தொலைபேசி எண்',
    'Remember Me': 'என்னை நினைவில் கொள்க',
    'Forgot Password?': 'கடவுச்சொல் மறந்துவிட்டதா?',
    'Sign In': 'உள்நுழைக',
    'Don\'t have an account?': 'கணக்கு இல்லையா?',
    'Sign up': 'பதிவுசெய்க',
    'Create an account': 'கணக்கை உருவாக்கவும்',
    'Sign up and start your smart farming journey': 'பதிவுசெய்து உங்கள் நவீன விவசாயப் பயணத்தைத் தொடங்குங்கள்',
    'Full name': 'முழு பெயர்',
    'Email': 'மின்னஞ்சல் முகவரி',
    'Phone': 'தொலைபேசி எண்',
    'Password': 'கடவுச்சொல்',
    'Confirm Password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'Farmer': 'விவசாயி',
    'Manager': 'மேலாளர்',
    'Farm Name': 'பண்ணை பெயர்',
    'Location': 'இருப்பிடம்',
    'Pin': 'வரைபடத்தில் குறி',
    'Farm Area': 'பண்ணை பரப்பளவு',
    'Unit': 'அலகு',
    'Hectares': 'ஹெக்டேர்',
    'Cents': 'சென்ட்',
    'I agree to AgriSense AI\'s': 'அகிரிசென்ஸ் AI இன்',
    'Terms & Conditions': 'விதிகள் மற்றும் நிபந்தனைகள்',
    'and Privacy Policy.': 'மற்றும் தனியுரிமைக் கொள்கையை ஏற்கிறேன்.',
    'Submit': 'சமர்ப்பி',
    'Have an account?': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'Terms & Conditions Agreement Required': 'விதிகள் மற்றும் நிபந்தனைகள் ஒப்புதல் தேவை',

    // Terms Modal & Direct Farm E-Commerce Translations
    'Terms of Service & Legal Agreements': 'சேவை விதிகள் & சட்ட ஒப்பந்தங்கள்',
    'Please review AgriSense AI platform policies and farm e-commerce terms.': 'அகிரிசென்ஸ் AI தளத்தின் கொள்கைகள் மற்றும் பண்ணை மின்-வணிக விதிகளை மதிப்பாய்வு செய்யவும்.',
    'Terms of Service': 'சேவை விதிகள்',
    'Privacy & Telemetry Policy': 'தனியுரிமை & தொலைஅளவியல் கொள்கை',
    'Direct Farm E-Commerce Terms': 'நேரடி பண்ணை மின்-வணிக விதிகள்',
    'Acceptance of Platform Terms': 'தளத்தின் விதிகளை ஏற்றுக்கொள்ளுதல்',
    'IoT Hardware & Sensor Telemetry Usage': 'IoT வன்பொருள் மற்றும் சென்சார் தரவு பயன்பாடு',
    'AI Crop Recommendation & Vision Diagnostic Disclaimer': 'AI பயிர் பரிந்துரை & நோய் கண்டறிதல் பொறுப்புத் துறப்பு',
    'Account Credentials & Security': 'கணக்கு சான்றுகள் & பாதுகாப்பு',
    'Limitation of Liability': 'பொறுப்பு வரம்பு',
    'Farm Data & Telemetry Ownership': 'பண்ணை தரவு மற்றும் தொலைஅளவியல் உரிமை',
    'Data Protection & Encryption': 'தரவு பாதுகாப்பு மற்றும் குறியாக்கம்',
    'Anonymized Model Training': 'அநாமதேய மாதிரி பயிற்சி',
    'Third-Party API Integrations': 'மூன்றாம் தரப்பு API இணைப்புகள்',
    'Direct Farm-to-Consumer (F2C) Model': 'நேரடி பண்ணை-நுகர்வோர் மாதிரி',
    'Produce Quality & Natural Variation': 'விளைபொருள் தரம் & இயற்கை வேறுபாடு',
    'Pricing, Invoicing & Escrow Security': 'விலை நிர்ணயம் & எஸ்க்ரோ பாதுகாப்பு',
    'Cancellation, Damaged Produce & Instant Refund Policy': 'ரத்துசெய்தல் & உடனடி பணத்தைத் திரும்பப்பெறுதல் கொள்கை',
    'Hyperlocal Delivery & Logistics': 'உள்ளூர் விநியோகம் & தளவாடங்கள்',
    'Close Document': 'ஆவணத்தை மூடு',
    'I Have Read & Accept Terms': 'நான் படித்தேன் & விதிகளை ஏற்கிறேன்',
    'Platform Terms & Direct Farm E-Commerce Guidelines': 'தள விதிகள் & நேரடி பண்ணை மின்-வணிக வழிகாட்டல்கள்',
    'Decline': 'நிராகரி',
    'By clicking agree, you accept all terms listed above.': 'ஏற்றுக்கொள்கிறேன் என்பதைக் கிளிக் செய்வதன் மூலம், மேலே பட்டியலிடப்பட்டுள்ள அனைத்து விதிகளையும் ஏற்கிறீர்கள்.',

    // Full Paragraph Translations for Terms & Legal Center
    'terms_p1': 'கணக்கை உருவாக்குவது, பண்ணை இடத்தை பதிவு செய்வது அல்லது IoT சென்சார்களை அகிரிசென்ஸ் AI உடன் இணைப்பதன் மூலம், இந்த சேவை விதிகளை ஏற்கிறீர்கள். வணிகப் பண்ணை அல்லது கூட்டுறவு அமைப்பின் சார்பில் செயல்பட்டால், அதற்கு உங்களுக்கு முழு அதிகாரம் உள்ளது என்பதை உறுதிப்படுத்துகிறீர்கள்.',
    'terms_p2': 'அகிரிசென்ஸ் AI ஆனது மண் ஈரப்பதம், NPK ஊட்டச்சத்துக்கள், வெப்ப நிலை, காற்றில் ஈரப்பதம் மற்றும் நீர் வால்வு நிலைகள் உள்ளிட்ட நேரடி சென்சார் அளவீடுகளைச் செயல்படுத்துகிறது.',
    'terms_p2_b1': 'சென்சார் வன்பொருளை சரியாக நிறுவி அளவீடு செய்வதற்கு பயனரே பொறுப்பாவார்.',
    'terms_p2_b2': 'தானியங்கி நீர்ப்பாசன பம்புகள் பயனரால் அமைக்கப்பட்ட வரம்புகள் அல்லது AI நேர அட்டவணைகளின்படி இயங்குகின்றன.',
    'terms_p2_b3': 'வன்பொருள் மின்தடை, வால்வு அடைப்பு அல்லது இணைய இணைப்பு இழப்புகளுக்கு அகிரிசென்ஸ் AI பொறுப்பல்ல.',
    'terms_p3_sub': 'விவசாய முடிவு ஆதரவு பொறுப்புத் துறப்பு',
    'terms_p3': 'அகிரிசென்ஸ் AI வழங்கும் AI பரிந்துரைகள் (பயிர் தேர்வு, நோய் கண்டறிதல், உர அளவுகள், நீர் அட்டவணைகள்) முடிவெடுக்கும் கருவிகள் மட்டுமே. இறுதி முடிவுகளும் பூச்சிக்கொல்லி பயன்பாடும் பயனரின் பொறுப்பாகும்.',
    'terms_p4': 'உங்கள் உள்நுழைவு விவரங்களை இரகசியமாக வைப்பதற்கு நீங்கள் பொறுப்பாவீர்கள். ஏதேனும் அங்கீகரிக்கப்படாத பயன்பாடு இருந்தால் உடனடியாக அகிரிசென்ஸ் AI க்கு தெரிவிக்க வேண்டும்.',
    'terms_p5': 'பயிர் விளைச்சல் வேறுபாடுகள், தீவிர வானிலை பயிர் இழப்பு அல்லது கணினி தாமதத்தினால் ஏற்படும் சேதங்களுக்கு அகிரிசென்ஸ் AI சட்டப்படி பொறுப்பல்ல.',
    'privacy_p1': 'உங்கள் பண்ணையின் எல்லைகள், மண் தரவு மற்றும் பயிர் விளைச்சல் தரவுகளுக்கு 100% நீங்களே உரிமையாளர். அகிரிசென்ஸ் AI உங்கள் தரவை விளம்பரதாரர்களுக்கு விற்பனை செய்யாது.',
    'privacy_p2': 'அனைத்து சென்சார் தரவு, REST API கோரிக்கைகள் மற்றும் பயனர் விவரங்கள் SSL/TLS மூலம் பாதுகாப்பாக குறியாக்கம் செய்யப்படுகின்றன.',
    'privacy_p3': 'உங்கள் தனிப்பட்ட விவரங்களை வெளிப்படுத்தாமல், AI மாதிரிகளை மேம்படுத்த மட்டுமே அநாமதேய மண் மற்றும் நோய் தரவு பயன்படுத்தப்படலாம்.',
    'privacy_p4': 'வானிலை அறிவிப்புகள் மற்றும் செயற்கைக்கோள் மண் ஈரப்பதம் தரவுகள் அங்கீகரிக்கப்பட்ட வானிலை சேவைகளின் இணைப்பை அடிப்படையாகக் கொண்டவை.',
    'ecom_p1': 'அகிரிசென்ஸ் AI சரிபார்க்கப்பட்ட உள்ளூர் விவசாயிகளை நேரடியாக நுகர்வோருடன் இணைக்கும் மின்-வணிக தளத்தை இயக்குகிறது. இடைத்தரகர்கள் இல்லாமல் விவசாயிகள் புதிய பழங்கள், காய்கறிகள் மற்றும் பண்ணை பொருட்களை வழங்குகிறார்கள்.',
    'ecom_p2': 'புதிய பண்ணை விளை பொருட்கள் இயற்கை முறையில் வடிவம், அளவு மற்றும் வண்ணத்தில் வேறுபடலாம். அறுவடை நேரத்தில் பொருட்கள் தரமாக இருப்பதை விவசாயிகள் உறுதி செய்கிறார்கள்.',
    'ecom_p3': 'பொருட்களின் விலைகள் விவசாயிகளால் நேரடியாக பட்டியலிடப்படுகின்றன. விநியோகம் முடியும் வரை கட்டணம் பாதுகாப்பாக எஸ்க்ரோவில் வைக்கப்படும்.',
    'ecom_p4_1': 'அழுகும் பொருட்கள் கொள்கை: பொருட்கள் அறுவடை/பேக் செய்யப்படுவதற்கு முன்பு வரை ஆர்டரை ரத்து செய்யலாம்.',
    'ecom_p4_2': 'ஏதேனும் பொருள் சேதமடைந்திருந்தால், 4 மணி நேரத்திற்குள் புகைப்படம் பதிவேற்றினால் 100% உடனடி ரீஃபண்ட் வழங்கப்படும்.',
    'ecom_p5': 'விநியோகங்கள் உள்ளூர் டெலிவரி கூட்டாளர்கள் அல்லது விவசாயிகள் மூலம் நேரடியாக பூர்த்தி செய்யப்படுகின்றன.',

    'Login': 'உள்நுழை',
    'Sign In': 'உள்நுழை',
    'Sign in': 'உள்நுழை',
    'Sign up / Create Account': 'பதிவு செய் / கணக்கை உருவாக்கு',
    'Step 1 of 4: Select Language': 'படி 1 / 4: மொழியைத் தேர்ந்தெடுக்கவும்',
    'Step 2 of 4: Personal Details': 'படி 2 / 4: தனிப்பட்ட விவரங்கள்',
    'Step 3 of 4: Security & Farm Details': 'படி 3 / 4: பாதுகாப்பு & பண்ணை விவரங்கள்',
    'Step 4 of 4: Terms & Complete Setup': 'படி 4 / 4: விதிகள் & பதிவு முடித்தல்',
    'Select Your Language': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    'Choose your preferred language for AgriSense AI': 'அகிரிசென்ஸ் AI பயன்பாட்டிற்கான உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    'Continue in': 'தொடர்க',
    'Step 1 of 3: Personal Details': 'படி 1 / 3: தனிப்பட்ட விவரங்கள்',
    'Step 2 of 3: Security & Farm Details': 'படி 2 / 3: பாதுகாப்பு & பண்ணை விவரங்கள்',
    'Step 3 of 3: Terms & Complete Setup': 'படி 3 / 3: விதிகள் & பதிவு முடித்தல்',
    'Next Step': 'அடுத்த படி',
    'Back': 'பின்செல்',
    'Review Your Details': 'உங்கள் விவரங்களை மதிப்பாய்வு செய்யவும்',
    'Complete Registration': 'பதிவை முடிக்கவும்',
    'Please fill out all personal details before proceeding.': 'தொடர்வதற்கு முன் அனைத்து தனிப்பட்ட விவரங்களையும் நிரப்பவும்.',
    'Passwords do not match.': 'கடவுச்சொற்கள் பொருந்தவில்லை.',
    'Please fill out all required fields before proceeding.': 'தொடர்வதற்கு முன் தேவையான அனைத்து புலங்களையும் நிரப்பவும்.',
  },
  hi: {
    'pH Level': 'पीएच स्तर',
    'Water Tank': 'पानी की टंकी',
    'Status': 'स्थिति',
    'OFF': 'बंद',
    'ON': 'चालू',
    'Sensor Overview': 'सेंसर अवलोकन',
    'AI Recommendations': 'एआई फसल सिफारिशें',
    'View All': 'सभी देखें',
    'Top 3 Suitable': 'शीर्ष 3 उपयुक्त',
    'Maize': 'मक्का',
    'Quick Actions': 'त्वरित कार्रवाई',
    'Recommendation': 'सिफारिश',
    'Field Telemetry &': 'खेत टेलीमेट्री एवं',
    'NODES ONLINE': 'नोड्स ऑनलाइन',
    'Manage Nodes': 'नोड्स प्रबंधित करें',
    'Field': 'खेत',
    'Polyhouse': 'पॉलीहाउस',
    'Drip Lines': 'ड्रिप लाइनें',
    'Battery': 'बैटरी',
    'Signal': 'सिग्नल',
    'View History': 'इतिहास देखें',
    'Result': 'परिणाम',
    'Severity': 'गंभीरता',
    'Confidence': 'विश्वास स्तर',
    'Mode': 'मोड',
    'Auto Mode': 'स्वचालित मोड',
    'Manual Mode': 'मैनुअल मोड',
    'Threshold': 'सीमा',
    'Next': 'अगला',
    'Tomorrow': 'कल',
    'Turn ON': 'चालू करें',
    'Turn OFF': 'बंद करें',
    'Alert': 'चेतावनी',
    'Overview': 'अवलोकन',
    'Water Usage': 'जल उपयोग',
    'Farm Map': 'फॉर्म मैप',
    'Farm': 'खेत',
    'Farms': 'खेत',
    'Crop': 'फसल',
    'Crops': 'फसलें',
    'Soil': 'मिट्टी',
    'Yield': 'उपज',
    'Harvest': 'कटाई',
    'Irrigation': 'सिंचाई',
    'Pumps': 'पंप',
    'Fertilizer': 'उर्वरक',
    'Nitrogen': 'नाइट्रोजन',
    'Phosphorus': 'फास्फोरस',
    'Potassium': 'पोटेशियम',
    'Weather': 'मौसम',
    'Forecast': 'पूर्वानुमान',
    'Rainfall': 'वर्षा',
    'Moisture': 'नमी',
    'Soil Moisture': 'मृदा नमी',
    'Soil pH': 'मृदा पीएच',
    'Temperature': 'तापमान',
    'Humidity': 'आर्द्रता',
    'Sensors': 'सेंसर',
    'Dashboard': 'डैशबोर्ड',
    'AI Advisor': 'एआई सलाहकार',
    'Diagnosis': 'रोग निदान',
    'Analytics': 'विश्लेषण',
    'Reports': 'रिपोर्ट',
    'Alerts': 'अलर्ट',
    'Devices': 'उपकरण',
    'Settings': 'सेटिंग्स',
    'Profile': 'प्रोफ़ाइल',
    'Run': 'चलाएं',
    'Start': 'प्रारंभ',
    'Stop': 'रोकें',
    'Edit': 'संपादित करें',
    'Save': 'सहेजें',
    'Delete': 'हटाएं',
    'Search': 'खोजें',
    'Optimal': 'इष्टतम',
    'Critical': 'गंभीर',
    'Connected': 'कनेक्टेड',
    'Disconnected': 'डिस्कनेक्ट किया गया',
    'Active': 'सक्रिय',
    'Offline': 'ऑफ़लाइन',
    'Online': 'ऑनलाइन',
    'Acre': 'एकड़',
    'Acres': 'एकड़',
    'greeting': 'शुभ प्रभात, साथी किसान! 👋',
    'search_placeholder': 'खोजें... (Ctrl + K)',
    'page_dashboard_title': 'मुख्य डैशबोर्ड',
    'page_dashboard_sub': 'लाइव सेंसर डेटा और एआई विश्लेषण',
  },
  te: {
    'pH Level': 'pH స్థాయి',
    'Water Tank': 'నీటి ట్యాంక్',
    'Status': 'స్థితి',
    'OFF': 'ఆఫ్',
    'ON': 'ఆన్',
    'Sensor Overview': 'సెన్సార్ అవలోకనం',
    'AI Recommendations': 'AI పంట సిఫార్సులు',
    'View All': 'అన్నీ చూడండి',
    'Field': 'పొలం',
    'Battery': 'బ్యాటరీ',
    'Signal': 'సిగ్నల్',
    'Mode': 'మోడ్',
    'Auto Mode': 'ఆటోమేటిక్ మోడ్',
    'Manual Mode': 'మ్యాన్యువల్ మోడ్',
    'Farm Map': 'వ్యవసాయ పటం',
    'Farm': 'పొలం',
    'Farms': 'పొలాలు',
    'Crop': 'పంట',
    'Crops': 'పంటలు',
    'Soil': 'నేల',
    'Yield': 'దిగుబడి',
    'Harvest': 'కోత',
    'Irrigation': 'నీటిపారుదల',
    'Pumps': 'పంప్‌లు',
    'Fertilizer': 'ఎరువులు',
    'Weather': 'వాతావరణం',
    'Moisture': 'తేమ',
    'Temperature': 'ఉష్ణోగ్రత',
    'Humidity': 'గాాలిలో తేమ',
    'Dashboard': 'డాష్‌బోర్డ్',
    'AI Advisor': 'AI సలహాదారు',
    'Diagnosis': 'వ్యాధి నిర్ధారణ',
    'Analytics': 'విశ్లేషణ',
    'Reports': 'నివేదికలు',
    'Alerts': 'హెచ్చరికలు',
    'Settings': 'సెట్టింగ్‌లు',
    'Search': 'శోధించండి',
    'greeting': 'శుభోదయం, రైతు సోదరా! 👋',
    'search_placeholder': 'శోధించండి... (Ctrl + K)',
  },
  kn: {
    'pH Level': 'pH ಮಟ್ಟ',
    'Water Tank': 'ನೀರಿನ ಟ್ಯಾಂಕ್',
    'Status': 'ಸ್ಥಿತಿ',
    'OFF': 'ಆಫ್',
    'ON': 'ಆನ್',
    'Sensor Overview': 'ಸೆನ್ಸರ್ ಸಮೀಕ್ಷೆ',
    'AI Recommendations': 'AI ಬೆಳೆ ಶಿಫಾರಸುಗಳು',
    'View All': 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    'Field': 'ಹೊಲ',
    'Battery': 'ಬ್ಯಾಟರಿ',
    'Signal': 'ಸಿಗ್ನಲ್',
    'Mode': 'ಮೋಡ್',
    'Auto Mode': 'ಸ್ವಯಂಚಾಲಿತ ಮೋಡ್',
    'Farm Map': 'ಫಾರ್ಮ್ ನಕ್ಷೆ',
    'Farm': 'ಫಾರ್ಮ್',
    'Farms': 'ಫಾರ್ಮ್‌ಗಳು',
    'Crop': 'ಬೆಳೆ',
    'Crops': 'ಬೆಳೆಗಳು',
    'Soil': 'ಮಣ್ಣು',
    'Yield': 'ಇಳುವರಿ',
    'Harvest': 'ಕೊಯ್ಲು',
    'Irrigation': 'ನೀರಾವರಿ',
    'Weather': 'ಹವಾಮಾನ',
    'Moisture': 'ತೇವಾಂಶ',
    'Temperature': 'ತಾಪಮಾನ',
    'Dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'AI Advisor': 'AI ಸಲಹೆಗಾರ',
    'Diagnosis': 'ರೋಗ ಪತ್ತೆ',
    'Analytics': 'ವಿಶ್ಲೇಷಣೆ',
    'Reports': 'ವರದಿಗಳು',
    'Settings': 'ಸಂಯೋಜನೆಗಳು',
    'greeting': 'ಶುಭೋದಯ, ರೈತ ಮಿತ್ರ! 👋',
    'search_placeholder': 'ಹುಡುಕಿ... (Ctrl + K)',
  },
  ml: {
    'pH Level': 'pH അളവ്',
    'Water Tank': 'ജലസംഭരണി',
    'Status': 'അവസ്ഥ',
    'OFF': 'ഓഫ്',
    'ON': 'ഓൺ',
    'Sensor Overview': 'സെൻസർ അവലോകനം',
    'AI Recommendations': 'AI വിള നിർദ്ദേശങ്ങൾ',
    'View All': 'എല്ലാം കാണുക',
    'Field': 'പാടം',
    'Battery': 'ബാറ്ററി',
    'Signal': 'സിഗ്നൽ',
    'Mode': 'മോഡ്',
    'Auto Mode': 'ഓട്ടോമാറ്റിക് മോഡ്',
    'Farm Map': 'ഫാം മാപ്പ്',
    'Farm': 'ഫാം',
    'Farms': 'ഫാമുകൾ',
    'Crop': 'വിള',
    'Crops': 'വിളകൾ',
    'Soil': 'മണ്ണ്',
    'Yield': 'വിളവ്',
    'Harvest': 'വിളവെടുപ്പ്',
    'Irrigation': 'ജലസേചനം',
    'Weather': 'കാലാവസ്ഥ',
    'Moisture': 'ഈർപ്പം',
    'Temperature': 'താപനില',
    'Dashboard': 'ഡാഷ്‌ബോർഡ്',
    'AI Advisor': 'AI ഉപദേശകൻ',
    'Diagnosis': 'രോഗനിർണ്ണയം',
    'Analytics': 'വിശകലനം',
    'Reports': 'റിപ്പോർട്ടുകൾ',
    'Settings': 'സജ്ജീകരണങ്ങൾ',
    'greeting': 'സുപ്രഭാതം, കർഷക മിത്രമേ! 👋',
    'search_placeholder': 'തിരയുക... (Ctrl + K)',
  }
};

// Standard English Page & Navigation Fallback Dictionary
export const EN_FALLBACK_DICTIONARY = {
  'greeting': 'Good Evening / Good Night, Aathi! 🌙',
  'greeting_morning': 'Good Morning, Aathi! 🌅',
  'greeting_afternoon': 'Good Afternoon, Aathi! ☀️',
  'greeting_evening': 'Good Evening, Aathi! 🌆',
  'greeting_night': 'Good Night, Aathi! 🌙',
  'search_placeholder': 'Search anything... (Ctrl + K)',
  'page_dashboard_title': 'Aathi (Lead Farmer)',
  'page_dashboard_sub': 'Coimbatore, Tamil Nadu • Live Telemetry Active',
  'page_farms_title': 'Farm Management',
  'page_farms_sub': 'Manage land plots, crops, and field assignments',
  'page_monitoring_title': 'Sensor Monitoring',
  'page_monitoring_sub': 'Real-time IoT telemetry readings and node health',
  'page_recommendation_title': 'AI Crop Advisor',
  'page_recommendation_sub': 'Machine learning agronomic crop recommendations',
  'page_diagnosis_title': 'Disease Diagnosis',
  'page_diagnosis_sub': 'AI vision crop leaf pathogen detector',
  'page_irrigation_title': 'Smart Irrigation',
  'page_irrigation_sub': 'Automated drip pump controls and schedules',
  'page_analytics_title': 'Analytics & Reports',
  'page_analytics_sub': 'Water usage, energy, and yield insights',
  'page_notifications_title': 'Alerts & Activity',
  'page_notifications_sub': 'System alerts and threshold notifications',
  'page_profile_title': 'User Profile',
  'page_profile_sub': 'Manage personal credentials and security settings',
  'page_settings_title': 'System Settings',
  'page_settings_sub': 'Configure units, alert thresholds, and API keys',
  'page_weather_title': 'Weather Forecast',
  'page_weather_sub': 'Real-time rain probability, humidity & micro-climate analysis',
  'nav_dashboard': 'Dashboard',
  'nav_farms': 'Farms',
  'nav_sensors': 'Sensors',
  'nav_irrigation': 'Irrigation',
  'nav_recommendation': 'AI Advisor',
  'nav_diagnosis': 'Diagnosis',
  'nav_analytics': 'Analytics',
  'nav_reports': 'Reports',
  'nav_notifications': 'Notifications',
  'nav_weather': 'Weather',
  'nav_devices': 'Devices',
  'nav_settings': 'Settings',
  'nav_mobile_showcase': 'Mobile App',

  // AI Advisor Keys
  'ai_crop_title': 'AI Crop Recommendation Engine',
  'ai_crop_subtitle': 'Machine learning agronomic crop recommendations based on soil & weather telemetry',
  'ai_micro_climate_inputs': 'Field Micro-Climate Telemetry',
  'ai_soil_ph': 'Soil pH Level',
  'ai_moisture': 'Soil Moisture',
  'ai_temp': 'Temperature',
  'ai_rainfall': 'Rainfall',
  'ai_run_recommendation': 'Run AI Recommendation',
  'ai_analyzing': 'Analyzing Micro-Climate Data...',
  'ai_recommended_crop': 'Recommended Crop',
  'ai_match_confidence': 'Agronomic Match Confidence'
};

// Build Bidirectional Reverse Lookup Engine (Any Language String -> English Key)
export const REVERSE_DICTIONARY = {};
Object.keys(FARMER_DICTIONARY).forEach((langCode) => {
  const dict = FARMER_DICTIONARY[langCode];
  Object.keys(dict).forEach((enKey) => {
    const translatedVal = dict[enKey];
    if (translatedVal && typeof translatedVal === 'string') {
      REVERSE_DICTIONARY[translatedVal.trim()] = enKey;
    }
  });
});

export const getTimeBasedGreetingKey = () => {
  const hour = new Date().getHours();
  if (hour >= 5 && hour < 12) return 'greeting_morning';
  if (hour >= 12 && hour < 17) return 'greeting_afternoon';
  if (hour >= 17 && hour < 21) return 'greeting_evening';
  return 'greeting_night';
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('agrisense_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('agrisense_lang', language);
  }, [language]);

  // Universal Bidirectional Translation Lookup Function
  const t = useCallback((text) => {
    if (!text) return '';
    if (typeof text !== 'string') return text;
    
    let trimmed = text.trim();

    // Auto-resolve dynamic time-based greeting if generic 'greeting' is passed
    if (trimmed === 'greeting') {
      trimmed = getTimeBasedGreetingKey();
    }

    // 1. If Target Language is English
    if (language === 'en') {
      if (EN_FALLBACK_DICTIONARY[trimmed]) {
        return EN_FALLBACK_DICTIONARY[trimmed];
      }
      if (REVERSE_DICTIONARY[trimmed]) {
        return REVERSE_DICTIONARY[trimmed];
      }
      return text;
    }

    // 2. Direct lookup in target language dictionary
    if (FARMER_DICTIONARY[language]?.[trimmed]) {
      return FARMER_DICTIONARY[language][trimmed];
    }

    // 3. Reverse lookup if input string is already translated into another language
    const enKey = REVERSE_DICTIONARY[trimmed];
    if (enKey) {
      if (FARMER_DICTIONARY[language]?.[enKey]) {
        return FARMER_DICTIONARY[language][enKey];
      }
      if (EN_FALLBACK_DICTIONARY[enKey]) {
        return EN_FALLBACK_DICTIONARY[enKey];
      }
      return enKey;
    }

    // 4. Fallback to English dictionary if key exists in EN_FALLBACK_DICTIONARY
    if (EN_FALLBACK_DICTIONARY[trimmed]) {
      return EN_FALLBACK_DICTIONARY[trimmed];
    }

    return text;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t,
    LANGUAGES
  }), [language, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'en',
      setLanguage: () => {},
      t: (text) => text || '',
      LANGUAGES
    };
  }
  return context;
};
